//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_app_parcing_ABP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasePool
    {
        public int Id { get; set; }
        public string complectation { get; set; }
        public string baseJSON { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<int> group { get; set; }
    
        public virtual Group Group1 { get; set; }
        public virtual Model Model { get; set; }
    }
}
