//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_app_parcing_ABP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database_test_scrapy_ABPEntities : DbContext
    {
        public Database_test_scrapy_ABPEntities()
            : base("name=Database_test_scrapy_ABPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Parts> Parts { get; set; }
        public virtual DbSet<SubGroup> SubGroup { get; set; }
        public virtual DbSet<BasePool> BasePool { get; set; }
    }
}
